// -----------------------------------------------------------------------------
// === การตั้งค่า Supabase ===
// 1. ไปที่ https://supabase.com สร้างโปรเจกต์ใหม่ฟรี
// 2. ไปที่ Project Settings -> API นำ URL และ anon key มาใส่ด้านล่าง
// 3. ไปที่ SQL Editor รันคำสั่งนี้เพื่อสร้างตาราง:
/*
  create table urls (
    id bigint generated by default as identity primary key,
    short_code text unique not null,
    original_url text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- เปิดสิทธิ์ให้ทุกคนสามารถอ่านและเขียนได้ (ตั้งค่า RLS)
  alter table urls enable row level security;
  create policy "Allow public insert" on urls for insert with check (true);
  create policy "Allow public read" on urls for select using (true);
*/
// -----------------------------------------------------------------------------

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Elements
const appContainer = document.getElementById('app');
const redirectingContainer = document.getElementById('redirecting');
const notFoundContainer = document.getElementById('not-found');
const shortenForm = document.getElementById('shorten-form');
const urlInput = document.getElementById('url-input');
const resultContainer = document.getElementById('result-container');
const shortUrlText = document.getElementById('short-url');
const copyBtn = document.getElementById('copy-btn');
const toast = document.getElementById('toast');
const submitBtn = shortenForm.querySelector('.btn');

// Initialize Supabase
let supabase;

try {
    supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} catch (error) {
    console.error("Supabase initialization error:", error);
}

// Check URL for Short Code (e.g. ?c=abcde)
const urlParams = new URLSearchParams(window.location.search);
const shortCode = urlParams.get('c');

if (shortCode) {
    // Redirect Mode
    handleRedirect(shortCode);
} else {
    // Main App Mode
    appContainer.style.display = 'flex';
}

async function handleRedirect(code) {
    redirectingContainer.classList.remove('hidden');

    if (!supabase) {
        alert('กรุณาตั้งค่า Supabase URL และ Key ในไฟล์ app.js ก่อนใช้งานระบบย่อลิ้ง');
        redirectingContainer.classList.add('hidden');
        appContainer.style.display = 'flex';
        return;
    }

    try {
        const { data, error } = await supabase
            .from('urls')
            .select('original_url')
            .eq('short_code', code)
            .single();

        if (error || !data) {
            console.error('Error fetching URL:', error);
            redirectingContainer.classList.add('hidden');
            notFoundContainer.classList.remove('hidden');
        } else {
            // Found it! Redirect
            window.location.replace(data.original_url);
        }
    } catch (err) {
        console.error('Redirect Exception:', err);
        redirectingContainer.classList.add('hidden');
        notFoundContainer.classList.remove('hidden');
    }
}

// Generate random short string (Base62)
function generateShortCode(length = 6) {
    const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
}

// Ensure URL has http(s) Protocol
function formatUrl(url) {
    if (!/^https?:\/\//i.test(url)) {
        return 'http://' + url;
    }
    return url;
}

// Handle Form Submit
shortenForm.addEventListener('submit', async (e) => {
    e.preventDefault();

    if (!supabase) {
        alert('กรุณาตั้งค่า Supabase URL และ Key ในไฟล์ app.js ก่อนใช้งานระบบย่อลิ้งครับ');
        return;
    }

    const originalUrl = formatUrl(urlInput.value.trim());
    if (!originalUrl) return;

    submitBtn.textContent = 'กำลังทำงาน...';
    submitBtn.disabled = true;

    try {
        // Create unique short code
        let code = generateShortCode();
        let isUnique = false;

        // Ensure uniqueness (simple retry loop)
        for (let i = 0; i < 3; i++) {
            const { data } = await supabase.from('urls').select('id').eq('short_code', code).maybeSingle();
            if (!data) {
                isUnique = true;
                break;
            }
            code = generateShortCode();
        }

        if (!isUnique) {
            throw new Error('ไม่สามารถสร้างโค้ดที่ไม่ซ้ำกันได้ ลองอีกครั้ง');
        }

        // Insert to Supabase
        const { error } = await supabase
            .from('urls')
            .insert([{ short_code: code, original_url: originalUrl }]);

        if (error) {
            console.error('Insert error:', error);
            alert('เกิดข้อผิดพลาดในการบันทึกข้อมูล กรุณาลองใหม่');
        } else {
            // Show result
            // Build the short URL based on the current domain
            const baseUrl = window.location.origin + window.location.pathname;
            const fullShortUrl = `${baseUrl}?c=${code}`;

            shortUrlText.textContent = fullShortUrl;
            shortUrlText.href = fullShortUrl;
            resultContainer.classList.remove('hidden');

            // Clear input
            urlInput.value = '';
        }
    } catch (err) {
        console.error('App Exception:', err);
        alert('เกิดข้อผิดพลาด กรุณาลองใหม่');
    } finally {
        submitBtn.textContent = 'ยืนยัน (ย่อลิ้ง)';
        submitBtn.disabled = false;
    }
});

// Copy to clipboard
copyBtn.addEventListener('click', async () => {
    const textToCopy = shortUrlText.textContent;
    try {
        await navigator.clipboard.writeText(textToCopy);
        toast.classList.remove('hidden');
        setTimeout(() => toast.classList.add('hidden'), 2000);
    } catch (err) {
        console.error('Failed to copy text: ', err);
        // Fallback
        const tempInput = document.createElement("input");
        tempInput.value = textToCopy;
        document.body.appendChild(tempInput);
        tempInput.select();
        document.execCommand("copy");
        document.body.removeChild(tempInput);

        toast.classList.remove('hidden');
        setTimeout(() => toast.classList.add('hidden'), 2000);
    }
});
